# Main script generate SciTextures  dataset

import os
import random
import secrets
import tools.MainFunctions as MF
from datetime import datetime
import tools.VisualQuestion as VQ
import json_pkl
import shutil
import re
import check_pbr_errors

##########################################Suggest models and simulations to generate patterns and implement them in code ###################################################################################3
def generate_scitextures(dataset_dir, query_dir, number_of_new=10, number_of_code_fix_retry=2, recheck_originality=True, idea_model="", code_model="", check_model="", model="gpt-5"):

    if idea_model == "": idea_model = model # model used to suggest ideas
    if code_model == "": code_model = model # model used for implement and debug code
    if check_model == "": check_model = model  # model used for checking the model generated by the coding model and find errors

    # its essential that benchmark_dir will be in relative path (it will later be converted into import)
    data_file = dataset_dir + "//data.pkl" # main data and log file  for the dataset contain all data code/descriptions
    data_file_back = dataset_dir + "//data_back.pkl"


    if not os.path.exists(dataset_dir): os.mkdir(dataset_dir) # output dir

    #=========load queries and prompts==========================
    dt={'qr': {}, "messages":[]} # Queries for the LVLMs (GPT)
    for fl in os.listdir(query_dir): # load queries from file
        dt['qr'][fl] = open(query_dir + "//" + fl, "r", encoding="utf-8").read()
    ######################################Suggest bencmarks################################################################################


    data_file_loaded=False # Loaded datafile
    if os.path.isfile(data_file):  # Load data file for the dataset
        print("\n\n\nLoad file\n\n\n")
        qr=dt['qr']
        dt=json_pkl.read_pkl(data_file)
        dt['qr']=qr
        data_file_loaded=True
        #............Removing unused............................................................................
        to_remove=[]
        if not 'benchmarks' in dt or dt['benchmarks'] is None: dt['benchmarks'] = {}
        for bname in dt['benchmarks']:
            ent = dt['benchmarks'][bname]
            if 'full_overlap' in ent and ent['full_overlap'] == True and 'code' not in ent:
                to_remove.append(bname)
            if not isinstance(ent , dict) or 'description' not in ent:
                to_remove.append(bname)
        for bname in to_remove:
                print("Removing:",bname)
                del dt['benchmarks'][bname]
        #,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,


#===========================Suggest new ideas and models==================================================================

    if  number_of_new>0: # Suggest ideas and models that
        print("\n\n\nSuggest Model for Patterns and Texture generations\n\n\n")
        txt=dt['qr']['suggest_benchmarks'].replace("@@@number_of_new@@@",str(number_of_new))
        if data_file_loaded: # prepare queries display exisiting models/methods in the dataset as part of the query (to avoid repetition)
            txt+=dt['qr']['add_suggestions']+ "\n Previous suggested methods: ["
            for ky in dt['benchmarks']:
                txt+=str(ky)+","
            txt+"]"

        resp,dt= VQ.get_reponse(dt, text=txt, model=idea_model) # suggest ideas for models and textures

#-----------------Convert ideas/suggestion to json dictionaries------------------------------------------------------------------------

        dt['benchmarks_text']=resp
        dt['messages'].append({"role": "user", "content":dt['qr']['suggestions_to_json']})
        benchmark_dic,dt = VQ.get_reponse(dt, messages=dt['messages'][-3:],as_json=True, model=idea_model)
        if 'benchmarks' in dt:
           for ky in benchmark_dic:
                if ky not in dt['benchmarks']:
                    dt['benchmarks'][ky]=benchmark_dic[ky]
                    print(benchmark_dic[ky])
                else:
                    print("error ", ky, "already exists")
        else:
           dt['benchmarks']=benchmark_dic
        json_pkl.save_pkl(dt,data_file)

#=================================Generate code for each suggested model separately ===================================================================================================
    if not 'benchmarks' in dt:
           dt['benchmarks'] = {}
    for bname in dt['benchmarks']:
        print("benchmark",bname)
        ent=dt['benchmarks'][bname]

        bdesc = ent["description"]


#------------------------------------------------------------------------------------------------------------

        if ('code' in ent) and ('code verified' in ent['code'] or 'finished_and_failed' in ent['code']): continue # if code already created and verified skip
        if 'full_overlap' in ent: continue # if overlap existing method continue

# -------------------------------Recheck idea originality optional recheck the idea is not already in the list of implemented models in the dataset -------------------------------------------------------------------------------------------------

        # ------------------------------------Implement method to code--------------------------------------------------------------------------------------

        code_query=dt['qr']['implement_code'].replace("**method_description**",bname).replace("**method_name**",bdesc).replace("Plus not less then 2 of (more is better)","In addition to at least 2 or more of the maps listed below:")+"\nSome of the maps can be uniform but at least 3 maps should be textured."
        if (not 'code' in ent) or ('Succeed' not in ent['code']):# or ent['code']['Succeed']=='no':
                    print("\n\n\nWrite code for:" + bname + "\n\n\n")
                    for gg in range(10):
                        print(code_query)
                        code_dic, dt = VQ.get_reponse(dt, text=code_query, as_json=True, model=code_model)
                        if ('code' in code_dic) and  ('Succeed' not in code_dic) and len(code_dic['code'])>100: code_dic['Succeed']="yes"
                        if ('Succeed' not in code_dic):
                      #       code_query+="\n\nIts very important that the output will be in the precise format described aboce\n\n"
                             continue
                        dt['benchmarks'][bname]['code'] = code_dic
                        dt['benchmarks'][bname]['code']['query'] = code_query
                        break
                    json_pkl.save_pkl(dt, data_file)
                    json_pkl.save_pkl(dt, data_file_back)

    #=============================Run Debug and validate code=========================================================

        #try:
        if ent['code']['Succeed']=='no': continue
        # except:
        #     d=3
        #     x=fsfs
        if 'code verified' not in ent['code'] or ent['code']['code verified']==False:
            print("\n\n\nTest and validate  code for:" + bname + "\n\n\n")
            sname = f"{re.sub(r'[^a-zA-Z]', '_', bname)}"
            dt['benchmarks'][bname]['simple name']= sname
            outcodedir= dataset_dir + "//" + sname + "//"
            sample_dir = outcodedir + "//textures//"
            dt['benchmarks'][bname]['dir'] = outcodedir

            #-----Validation code run the generator and test results----------------------------
            texture_size =512
            numsamples =10
            testing_code_str = (
                        #"\nimport importlib\n" +
                        #"\nimport " + MF.path_to_import(code_path) + " as generate\n" +
                        #code_path.replace("//",".").replace(".py","").replace("/",".").replace("..",".") + " as generate\n"+

                        "\nimport importlib, os, sys"
                        "\nsubdir = '" + outcodedir + "'"
                        "\nsys.path.clear()"
                        "\nsys.path.insert(0, os.path.abspath(subdir))"
                        "\nimport generate  as generate"                                                                        
                        "\nimportlib.reload(generate)"
                        "\noutdir = '" + sample_dir + "'" +
                        "\ngenerate.generate_texture(outdir, sz="+str(texture_size)+",numsamples="+str(numsamples)+")"
            )



            for kk in range(number_of_code_fix_retry+100):
                if not os.path.exists(dataset_dir): os.mkdir(outcodedir)
                code = dt['benchmarks'][bname]['code']['code']
            ###    code_generation_talk=dt['messages'][-2:]
                ln=len(dt['messages'])


               #-------------------Run code and debug---------------------------------------------------------------------------
                code_verified, path, test_dir, code, captured_stdout, messages = (
                MF.run_debug_code(messages =dt['messages'][-2:], code=code,
                                  code_dir=outcodedir, functions_and_var={}, codefilename="generate.py",
                                  testing_code=testing_code_str, task_description=bdesc, time_out = 900, rechek_code=False, model=code_model))


                with open(test_dir+"//Description.txt","w") as fl: fl.write(bdesc) # write benchmark description
                if  "overlap" in ent:
                     json_pkl.save_json(ent["overlap"],test_dir+"//overlap.txt")

   #=======================================================================================================================
                #...........Recheck codes and identify errors .................................................
                find_error, error_message = check_pbr_errors.verify_pbr_output(
                    outdir=sample_dir,
                numsamples =numsamples,
                sz=texture_size)
                find_error = False
                #...............Run of code and collect tesults...................................
                if not code_verified:
                    dt['messages']=dt['messages'][:ln]
                    #continue
                    break
                txt = "\n\n\n***Your task:***\n" + dt['qr']['check_code']
                txt +="***Original Code Generation task:***\n"+code_query+"\n\n\n"
                txt+="***Generated Code***:\n"+code+"\n\n\n"
                txt+="The code run on time and did not crash.\n"
                if find_error:
                     txt+="However inspecting the output dir find the following problems/errors:\n"+error_message
                else:
                    txt+="Automatic inspection: The files/folders structure and names and image size produce are  correct.\n"
                 # limit the number of attempt to fixe the code otherwise you might be stack in endless loop

                if kk >= number_of_code_fix_retry and not find_error: break # give it more tries if you identify obvious errors in output
                if kk >= number_of_code_fix_retry+3: break # if there error try multiple times

                verify_query=txt
                print(txt)
                code_dic, dt = VQ.get_reponse(dt, text=verify_query, as_json=True, model=check_model) # Ask the checker LLM to identify and correct errors
    #            print(dt['benchmarks'][bname]['code']['discussion'])
                if 'corrections' in code_dic and code_dic['corrections']=='yes':# and len(code_dic['code'])>0:
                    print("\\n\n\n****************************************************************************\n\n\nCode correction found:",code_dic)
                    del dt['benchmarks'][bname]['code']
                    dt['benchmarks'][bname]['code'] = code_dic
                    dt['benchmarks'][bname]['code']['Succeed'] = 'yes'
                    dt['benchmarks'][bname]['code']['query'] = code_query
                    dt['benchmarks'][bname]['code']['fixing_query'] = verify_query

                else:
                    break


                #......................................

 # Finish generatin one entry  Write to file

            dt['benchmarks'][bname]['code']['code verified'] = code_verified
            if not code_verified: dt['benchmarks'][bname]['code']['finished_and_failed']=True
          ###  dt['benchmarks'][bname]['code']['code'] = code
            json_pkl.save_pkl(dt, data_file)
            json_pkl.save_pkl(dt, data_file_back)
            print("\n\n\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\nFinished benchmark ",bname,"\nverified ",code_verified,"\n\n\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\n")


################################################################################################################################################################

if __name__=="__main__":

        models = ["google/gemini-3.1-flash-lite-preview","z-ai/glm-5.1", "moonshotai/kimi-k2.6","openai/gpt-5.5", "openai/gpt-5.4","qwen/qwen3.6-max-preview","xiaomi/mimo-v2.5-pro","deepseek/deepseek-v4-pro","google/gemini-3.1-pro-preview","xiaomi/mimo-v2.5-pro","minimax/minimax-m2.7","anthropic/claude-sonnet-4.6","openai/gpt-5.4","openai/gpt-5.5","x-ai/grok-4.3"]
        main_query_dir= "queries_prompts/"
      #  queries = os.listdir(main_query_dir)
        queries =['pbr_complex_original']#'pbr_social_science', 'pbr_biology', 'pbr_phsyics_engineering', 'pbr_creative', 'pbr_math']
        print(queries)

        for ii in range(1000):
            topic = random.choice(queries)
            query_dir = os.path.join("queries_prompts",topic)  # Folder where prompts/queries are save
            outputdir = topic +"//"  # output folder where the generated dataset will be saved,
            if not os.path.exists(outputdir): os.makedirs(outputdir)
            data_file = outputdir + "//data.pkl" # Data file contain all data in the dataset

            number_of_code_fix_retry = 0  # 3 # number of times to try to fix code before accepting the final results (note that over analyzing the code often make the results wors
            recheck_originality=False #True # double check the idea is in dataset also identify related ideas
            #xiaomi/mimo-v2.5-pro #xiaomi/mimo-v2.5-pro"])#"google/gemini-3.1-pro-preview"])#"
            model = random.choice(["openai/gpt-5.4"])#"moonshotai/kimi-k2.6"])#"google/gemini-3.1-flash-lite-preview","moonshotai/kimi-k2.6","xiaomi/mimo-v2.5-pro"])#,"openai/gpt-5.4","openai/gpt-5.5","google/gemini-3.1-pro-preview"])#"openai/gpt-5.5"])#"google/gemini-3.1-flash-lite-preview"#"openai/gpt-5.4"#google/gemini-3.1-flash-lite-preview"#"z-ai/glm-5.1"#"google/gemini-3.1-flash-lite-preview"#"z-ai/glm-5.1"#google/gemini-3.1-flash-lite-preview"#"z-ai/glm-5.1"## "google/gemini-3.1-flash-lite-preview"#"google/gemini-3-flash-preview" # model for writing code (and defult for everthing else) "z-ai/glm-4.7-flash"#"moonshotai/kimi-k2.6"#openai/gpt-5.2"#grok-4-fast-reasoning"#"Qwen/Qwen2.5-VL-72B-Instruct"#"claude-sonnet-4-5-20250929" #"grok-4-fast-reasoning"#"gemini-2.5-flash"#"Qwen/Qwen2.5-VL-72B-Instruct"#"gpt-5"
            idea_model =   random.choice(models)
            number_of_new= 5 # Number of new ideas to suggest in each round
            print(datetime.now())
            print("\n*************************\n"+idea_model,model,query_dir,"\n********************************\n")
            try:
                generate_scitextures(dataset_dir=outputdir, query_dir=query_dir, number_of_new=number_of_new, number_of_code_fix_retry=number_of_code_fix_retry, recheck_originality=recheck_originality, model=model, idea_model = idea_model)
            except Exception as e:
                print(e)
# 301.4$
# 121 items in general 00:00